---
kind: Mesh
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: app-name
  namespace: app-namespace
spec:
  compartmentId: ocid1.compartment.oc1..aaaaaaaajyowfbrbhj4rzpzx26hbmzlegcn7mhfgctmqxvwasyeeylqlchda
  certificateAuthorities:
    - id: ocid1.certificateauthority.oc1.iad.aaa...
  mtls:
    minimum: PERMISSIVE
---
kind: VirtualService
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: ms1
  namespace: app-namespace
spec:
  mesh:
    ref:
      name: app-name

  defaultRoutingPolicy:
    type: UNIFORM
  compartmentId: ocid1.compartment.oc1..aaaaaaaajyowfbrbhj4rzpzx26hbmzlegcn7mhfgctmqxvwasyeeylqlchda

  hosts:
    - ms1
    - ms1:9080
---
kind: VirtualDeployment
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: ms1
  namespace: app-namespace
spec:
  virtualService:
    ref:
      name: ms1
  compartmentId: ocid1.compartment.oc1..aaaaaaaajyowfbrbhj4rzpzx26hbmzlegcn7mhfgctmqxvwasyeeylqlchdaocid1.compartment.oc1..aaaa...
  listener:
    - port: 9080
      protocol: HTTP
  accessLogging:
    isEnabled: true
  serviceDiscovery:
    type: DNS
    hostname: ms1
---
apiVersion: servicemesh.oci.oracle.com/v1beta1
kind: VirtualServiceRouteTable
metadata:
  name: ms1-route-table
  namespace: app-namespace
spec:
  compartmentId: ocid1.compartment.oc1..aaaaaaaajyowfbrbhj4rzpzx26hbmzlegcn7mhfgctmqxvwasyeeylqlchda
  virtualService:
    ref:
      name: ms1
  routeRules:
    - httpRoute:
        destinations:
          - virtualDeployment:
              ref:
                name: ms1
            weight: 100
---
kind: VirtualService
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: ms2
  namespace: app-namespace
spec:
  mesh:
    ref:
      name: app-name

  defaultRoutingPolicy:
    type: UNIFORM
  compartmentId: ocid1.compartment.oc1..aaaaaaaajyowfbrbhj4rzpzx26hbmzlegcn7mhfgctmqxvwasyeeylqlchda

  hosts:
    - ms2
    - ms2:9080
    - ms2:9081
---
kind: VirtualDeployment
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: ms2-v1
  namespace: app-namespace
spec:
  virtualService:
    ref:
      name: ms2
  compartmentId: ocid1.compartment.oc1..aaaaaaaajyowfbrbhj4rzpzx26hbmzlegcn7mhfgctmqxvwasyeeylqlchda
  listener:
    - port: 9080
      protocol: HTTP
    - port: 9081
      protocol: GRPC
  accessLogging:
    isEnabled: true
  serviceDiscovery:
    type: DNS
    hostname: ms2-v1
---
kind: VirtualDeployment
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: ms2-v2
  namespace: app-namespace
spec:
  virtualService:
    ref:
      name: ms2
  compartmentId: ocid1.compartment.oc1..aaaa...
  listener:
    - port: 9080
      protocol: HTTP
    - port: 9081
      protocol: GRPC
  accessLogging:
    isEnabled: true
  serviceDiscovery:
    type: DNS
    hostname: ms2-v2
---
apiVersion: servicemesh.oci.oracle.com/v1beta1
kind: VirtualServiceRouteTable
metadata:
  name: ms2-route-table
  namespace: app-namespace
spec:
  compartmentId: ocid1.compartment.oc1..aaaaaaaajyowfbrbhj4rzpzx26hbmzlegcn7mhfgctmqxvwasyeeylqlchda
  virtualService:
    ref:
      name: ms2
  routeRules:
    - httpRoute:
        destinations:
          - virtualDeployment:
              ref:
                name: ms2-v1
            weight: 50
          - virtualDeployment:
              ref:
                name: ms2-v2
            weight: 50
---
kind: VirtualService
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: ui
  namespace: app-namespace
spec:
  mesh:
    ref:
      name: app-name

  defaultRoutingPolicy:
    type: UNIFORM
  compartmentId: ocid1.compartment.oc1..aaaaaaaajyowfbrbhj4rzpzx26hbmzlegcn7mhfgctmqxvwasyeeylqlchda

  hosts:
    - ui
    - ui:9080
---
kind: VirtualDeployment
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: ui
  namespace: app-namespace
spec:
  virtualService:
    ref:
      name: ui
  compartmentId: ocid1.compartment.oc1..aaaaaaaajyowfbrbhj4rzpzx26hbmzlegcn7mhfgctmqxvwasyeeylqlchda
  listener:
    - port: 9080
      protocol: HTTP
  accessLogging:
    isEnabled: true
  serviceDiscovery:
    type: DNS
    hostname: ui
---
apiVersion: servicemesh.oci.oracle.com/v1beta1
kind: VirtualServiceRouteTable
metadata:
  name: ui-route-table
  namespace: app-namespace
spec:
  compartmentId: ocid1.compartment.oc1..aaaaaaaajyowfbrbhj4rzpzx26hbmzlegcn7mhfgctmqxvwasyeeylqlchda
  virtualService:
    ref:
      name: ui
  routeRules:
    - httpRoute:
        destinations:
          - virtualDeployment:
              ref:
                name: ui
            weight: 100
---
kind: IngressGateway
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: app-name-ingress-gateway
  namespace: app-namespace
spec:
  compartmentId: ocid1.compartment.oc1..aaaaaaaajyowfbrbhj4rzpzx26hbmzlegcn7mhfgctmqxvwasyeeylqlchda
  mesh:
    ref:
      name: app-name
  hosts:
    - name: exampleHost
      hostnames:
        - hostname.example.com
        - hostname.example.com:80
        - hostname.example.com:443
      listeners:
        - port: 9080
          protocol: HTTP
          tls:
            serverCertificate:
              ociTlsCertificate:
                certificateId: ocid1.certificate.oc1.iad.aaa...
            mode: TLS
  accessLogging:
    isEnabled: true
---
apiVersion: servicemesh.oci.oracle.com/v1beta1
kind: IngressGatewayRouteTable
metadata:
  name: app-name-ingress-gateway-route-table
  namespace: app-namespace
spec:
  compartmentId: ocid1.compartment.oc1..aaaa...
  ingressGateway:
    ref:
      name: app-name-ingress-gateway
  routeRules:
    - httpRoute:
        ingressGatewayHost:
          name: exampleHost
        destinations:
          - virtualService:
              ref:
                name: ui
---
kind: AccessPolicy
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: app-name-policy
  namespace: app-namespace
spec:
  mesh:
    ref:
      name: app-name
  compartmentId: ocid1.compartment.oc1..aaaaaaaajyowfbrbhj4rzpzx26hbmzlegcn7mhfgctmqxvwasyeeylqlchda
  rules:
    - action: ALLOW
      source:
        virtualService:
          ref:
            name: <vs-sample-page>
      destination:
        allVirtualServices: {}
    - action: ALLOW
      source:
        ingressGateway:
          ref:
            name: <sample-ingress-gateway>
      destination:
        virtualService:
          ref:
            name: <vs-sample-page>
---